#pragma once

namespace puma
{
    const std::map<InputID, const char*> kInputNames = {
        {InputID::MB_Left           ,"LBM"          },
        {InputID::MB_Middle         ,"MMB"          },
        {InputID::MB_Right          ,"RMB"          },
        {InputID::MB_X1             ,"MB4"          },
        {InputID::MB_X2             ,"MB5"          },
        {InputID::KB_RETURN         ,"Enter"        },
        {InputID::KB_ESCAPE         ,"ESC"          },
        {InputID::KB_BACKSPACE      ,"Backspace"    },
        {InputID::KB_TAB            ,"TAB"          },
        {InputID::KB_SPACE          ,"SPACE"        },
        {InputID::KB_EXCLAIM        ,"!"            },
        {InputID::KB_QUOTEDBL       ,"\""           },
        {InputID::KB_HASH           ,"#"            },
        {InputID::KB_PERCENT        ,"%"            },
        {InputID::KB_DOLLAR         ,"$"            },
        {InputID::KB_AMPERSAND      ,"&"            },
        {InputID::KB_QUOTE          ,"'"            },
        {InputID::KB_LEFTPAREN      ,"("            },
        {InputID::KB_RIGHTPAREN     ,")"            },
        {InputID::KB_ASTERISK       ,"*"            },
        {InputID::KB_PLUS           ,"+"            },
        {InputID::KB_COMMA          ,","            },
        {InputID::KB_MINUS          ,"-"            },
        {InputID::KB_PERIOD         ,"."            },
        {InputID::KB_SLASH          ,"/"            },
        {InputID::KB_0              ,"0"            },
        {InputID::KB_1              ,"1"            },
        {InputID::KB_2              ,"2"            },
        {InputID::KB_3              ,"3"            },
        {InputID::KB_4              ,"4"            },
        {InputID::KB_5              ,"5"            },
        {InputID::KB_6              ,"6"            },
        {InputID::KB_7              ,"7"            },
        {InputID::KB_8              ,"8"            },
        {InputID::KB_9              ,"9"            },
        {InputID::KB_COLON          ,":"            },
        {InputID::KB_SEMICOLON      ,";"            },
        {InputID::KB_LESS           ,"<"            },
        {InputID::KB_EQUALS         ,"="            },
        {InputID::KB_GREATER        ,">"            },
        {InputID::KB_QUESTION       ,"?"            },
        {InputID::KB_AT             ,"@"            },
        {InputID::KB_LEFTBRACKET    ,"["            },
        {InputID::KB_BACKSLASH      ,"\\"           },
        {InputID::KB_RIGHTBRACKET   ,"]"            },
        {InputID::KB_CARET          ,"^"            },
        {InputID::KB_UNDERSCORE     ,"_"            },
        {InputID::KB_BACKQUOTE      ,"`"            },
        {InputID::KB_A              ,"A"            },
        {InputID::KB_B              ,"B"            },
        {InputID::KB_C              ,"C"            },
        {InputID::KB_D              ,"D"            },
        {InputID::KB_E              ,"E"            },
        {InputID::KB_F              ,"F"            },
        {InputID::KB_G              ,"G"            },
        {InputID::KB_H              ,"H"            },
        {InputID::KB_I              ,"I"            },
        {InputID::KB_J              ,"J"            },
        {InputID::KB_K              ,"K"            },
        {InputID::KB_L              ,"L"            },
        {InputID::KB_M              ,"M"            },
        {InputID::KB_N              ,"N"            },
        {InputID::KB_O              ,"O"            },
        {InputID::KB_P              ,"P"            },
        {InputID::KB_Q              ,"Q"            },
        {InputID::KB_R              ,"R"            },
        {InputID::KB_S              ,"S"            },
        {InputID::KB_T              ,"T"            },
        {InputID::KB_U              ,"U"            },
        {InputID::KB_V              ,"V"            },
        {InputID::KB_W              ,"W"            },
        {InputID::KB_X              ,"X"            },
        {InputID::KB_Y              ,"Y"            },
        {InputID::KB_Z              ,"Z"            },
        {InputID::KB_CAPSLOCK       ,"CAPSLOCK"     },
        {InputID::KB_F1             ,"F1"           },
        {InputID::KB_F2             ,"F2"           },
        {InputID::KB_F3             ,"F3"           },
        {InputID::KB_F4             ,"F4"           },
        {InputID::KB_F5             ,"F5"           },
        {InputID::KB_F6             ,"F6"           },
        {InputID::KB_F7             ,"F7"           },
        {InputID::KB_F8             ,"F8"           },
        {InputID::KB_F9             ,"F9"           },
        {InputID::KB_F10            ,"F10"          },
        {InputID::KB_F11            ,"F11"          },
        {InputID::KB_F12            ,"F12"          },
        {InputID::KB_PRINTSCREEN    ,"PRTSCRN"      },
        {InputID::KB_SCROLLLOCK     ,"SCROLLLOCK"   },
        {InputID::KB_PAUSE          ,"PAUSE"        },
        {InputID::KB_INSERT         ,"INSERT"       },
        {InputID::KB_HOME           ,"HOME"         },
        {InputID::KB_PAGEUP         ,"PAGEUP"       },
        {InputID::KB_DELETE         ,"DELETE"       },
        {InputID::KB_END            ,"END"          },
        {InputID::KB_PAGEDOWN       ,"PAGEDOWN"     },
        {InputID::KB_RIGHT          ,"RIGHT"        },
        {InputID::KB_LEFT           ,"LEFT"         },
        {InputID::KB_DOWN           ,"DOWN"         },
        {InputID::KB_UP             ,"UP"           },
        {InputID::KB_NUMLOCKCLEAR   ,"NUMLOCK"      },
        {InputID::KB_NUM_DIVIDE     ,"NUM /"        },
        {InputID::KB_NUM_MULTIPLY   ,"NUM *"        },
        {InputID::KB_NUM_MINUS      ,"NUM -"        },
        {InputID::KB_NUM_PLUS       ,"NUM +"        },
        {InputID::KB_NUM_ENTER      ,"NUM ENTER"    },
        {InputID::KB_NUM_1          ,"NUM 1"        },
        {InputID::KB_NUM_2          ,"NUM 2"        },
        {InputID::KB_NUM_3          ,"NUM 3"        },
        {InputID::KB_NUM_4          ,"NUM 4"        },
        {InputID::KB_NUM_5          ,"NUM 5"        },
        {InputID::KB_NUM_6          ,"NUM 6"        },
        {InputID::KB_NUM_7          ,"NUM 7"        },
        {InputID::KB_NUM_8          ,"NUM 8"        },
        {InputID::KB_NUM_9          ,"NUM 9"        },
        {InputID::KB_NUM_0          ,"NUM 0"        },
        {InputID::KB_NUM_PERIOD     ,"NUM ."        },
        {InputID::KB_APPLICATION    ,"APPLICATION"  },
        {InputID::KB_LCTRL          ,"LCTRL"        },
        {InputID::KB_LSHIFT         ,"LSHIFT"       },
        {InputID::KB_LALT           ,"LALT"         },
        {InputID::KB_LGUI           ,"LGUI"         },
        {InputID::KB_RCTRL          ,"RCTRL"        },
        {InputID::KB_RSHIFT         ,"RSHIFT"       },
        {InputID::KB_RALT           ,"RALT"         },
        {InputID::KB_RGUI           ,"RGUI"         },
    };
}